MddInterviewProject/Models/Comment.cs
namespace MddInterviewProject.Models
{
    public class Comment
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Body { get; set; }
    }
}

MddInterviewProject/Models/Post.cs
using System.Collections.Generic;

namespace MddInterviewProject.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public List<Comment> Comments { get; set; }
    }
}

MddInterviewProject/Controllers/PostsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using MddInterviewProject.Services;

namespace MddInterviewProject.Controllers
{
    public class PostsController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly ILogger _logger;
        
        public PostsController(IBlogService blogService, ILogger logger)
        {
            _blogService = blogService;
            _logger = logger;
        }
        
        public async Task<ActionResult> Index()
        {
            var posts = await _blogService.GetPostsAndCommentsAsync();
            return View(posts);
        }
    }
}

MddInterviewProject/Views/Posts/Index.cshtml
@model System.Collections.Generic.List<MddInterviewProject.Models.Post>

@{
    ViewBag.Title = "title";
    Layout = "../Shared/_Layout.cshtml";
}

<h3>Blog</h3>
<ul>
    @foreach (var post in @Model)
    {
        <li>
            @Html.Partial("_Post", post)
        </li>   
    }
</ul>

MddInterviewProject/Views/Posts/_Comment.cshtml
@model MddInterviewProject.Models.Comment

<li>
    <p>@Model.Body</p>
</li>

MddInterviewProject/Views/Posts/_Post.cshtml
@model MddInterviewProject.Models.Post

 <div class="post">
            <h4>@Model.Id @Model.Title</h4>
                <p>@Model.Body</p>
                <div class="comments">
                    <ul>
                        @foreach(var comment in Model.Comments)
                        {
                            @Html.Partial("_Comment", comment)
                        }
                    </ul>
                </div>
            </div>

MddInterviewProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mdd Interview App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Posts", new { area = "" }, new { @class = "navbar-brand" })
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>